
language: python
python:
  - "2.7"
  - "3.5"

# command to install dependencies
install:
  - pip install -e .[test]

# command to run tests
script: 
  - py.test src --cov=src --cov-report term-missing

# safelist
branches:
  only:
  - quick_sort

notifications:
  email: false

after_success:
  - coveralls
